"""added email field

Revision ID: 0404bfd851bf
Revises: 0f2778ea92c0
Create Date: 2026-09-12 21:41:01.969070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0404bfd851bf'
down_revision: Union[str, Sequence[str], None] = '0f2778ea92c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'table_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_users', type_='unique')
    op.drop_column('table_users', 'email')
    # ### end Alembic commands ###
