"""added passwords to users

Revision ID: 0f2778ea92c0
Revises: b8f73c54fa8d
Create Date: 2026-09-11 21:42:43.596163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2778ea92c0'
down_revision: Union[str, Sequence[str], None] = 'b8f73c54fa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_users', 'password')
    # ### end Alembic commands ###
