"""added age surname and fullname into users model

Revision ID: 24117b02ba0b
Revises: 0404bfd851bf
Create Date: 2026-09-14 15:00:34.034026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24117b02ba0b'
down_revision: Union[str, Sequence[str], None] = '0404bfd851bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('table_users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('table_users', sa.Column('age', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('table_users_name_key'), 'table_users', type_='unique')
    op.create_unique_constraint(None, 'table_users', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_users', type_='unique')
    op.create_unique_constraint(op.f('table_users_name_key'), 'table_users', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('table_users', 'age')
    op.drop_column('table_users', 'full_name')
    op.drop_column('table_users', 'surname')
    # ### end Alembic commands ###
