"""fix delete

Revision ID: 2beec5fe5408
Revises: f30fef685909
Create Date: 2026-09-09 18:19:00.687713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2beec5fe5408'
down_revision: Union[str, Sequence[str], None] = 'f30fef685909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('table_products_user_id_fkey'), 'table_products', type_='foreignkey')
    op.create_foreign_key(None, 'table_products', 'table_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_products', type_='foreignkey')
    op.create_foreign_key(op.f('table_products_user_id_fkey'), 'table_products', 'table_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
