"""change id type for products

Revision ID: 4067725638e3
Revises: f3fcee4e597f
Create Date: 2026-09-09 18:54:00.104887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4067725638e3'
down_revision: Union[str, Sequence[str], None] = 'f3fcee4e597f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_products', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('table_products_user_id_fkey'), 'table_products', type_='foreignkey')
    op.create_foreign_key(None, 'table_products', 'table_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_products', type_='foreignkey')
    op.create_foreign_key(op.f('table_products_user_id_fkey'), 'table_products', 'table_users', ['user_id'], ['id'])
    op.alter_column('table_products', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
