"""added associate table catalogues

Revision ID: b8f73c54fa8d
Revises: 4067725638e3
Create Date: 2026-09-09 22:56:48.891670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f73c54fa8d'
down_revision: Union[str, Sequence[str], None] = '4067725638e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_catalogues',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_catalogue_assoc',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('catalogue_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_id'], ['table_catalogues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['table_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'catalogue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_catalogue_assoc')
    op.drop_table('table_catalogues')
    # ### end Alembic commands ###
