"""added admin checking

Revision ID: e03985be6e47
Revises: 24117b02ba0b
Create Date: 2026-09-14 17:13:11.580204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03985be6e47'
down_revision: Union[str, Sequence[str], None] = '24117b02ba0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_users', 'admin')
    # ### end Alembic commands ###
